services:
  mosquitto_init:
    image: eclipse-mosquitto:2.0.20
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - mosquitto-conf:/mosquitto-conf
      - ./mosquitto/:/init-conf/
    command: >
      sh -c "echo 'Create configurations for mosquitto server'
      && cp /init-conf/mosquitto.conf /mosquitto-conf/mosquitto.conf
      && touch /mosquitto-conf/passwd
      && chmod 0700 /mosquitto-conf/passwd
      && mosquitto_passwd -b /mosquitto-conf/passwd ${MQTT_USER} ${MQTT_PASSWORD}
      && echo 'Done!'"
    restart: no

  mosquitto:
    image: eclipse-mosquitto:2.0.20
    volumes:
      - mosquitto-conf:/mosquitto/config/
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
    depends_on:
      mosquitto_init:
        condition: service_completed_successfully
    restart: always
    deploy:
      resources:
        limits:
          memory: 32M


  homebridge:
    image: homebridge/homebridge:2025-01-11
    environment:
      - TZ=Europe/Helsinki
    network_mode: host
    volumes:
      - ${DATA_DIR}/homebridge:/homebridge
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  z2m:
    image: koenkk/zigbee2mqtt:2.1.1
    environment:
      - TZ=Europe/Helsinki
    group_add:
    - dialout
    user: ${LOCAL_UID}:${LOCAL_GID}
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_DIR}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - ${ADAPTER_PATH}:/dev/ttyACM0
    depends_on:
      - mosquitto
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  node-red:
    image: nodered/node-red:4.0.8-22-minimal
    environment:
      - TZ=Europe/Helsinki
    user: ${LOCAL_UID}:${LOCAL_GID}
    ports:
      - "1880:1880"
    volumes:
      - ${DATA_DIR}/node-red:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:7.4.2-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 32M


volumes:
  mosquitto-conf: